fix: panic when lance.auto_cleanup.interval is set to 0 (#5571)
For now, when lance.auto_cleanup.interval is set to 0, dataset commits
panic with a "division by zero" error:

```
thread 'dataset::cleanup::tests::test_auto_cleanup_interval_zero' panicked at rust/lance/src/dataset/cleanup.rs:672:12:
attempt to calculate the remainder with a divisor of zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

To fix the panic, we can interpret `lance.auto_cleanup.interval = 0` as
triggering cleanup after each commit, which is equivalent to
`lance.auto_cleanup.interval = 1`