feat: add `py.typed` marker file (#5479)
Hey,

currently, this package is somewhat type hinted, but unfortunately, the
`py.typed` marker file is missing which is a
[MUST](https://typing.python.org/en/latest/spec/distributing.html#packaging-type-information)
to signal that a package can be used for type hinting for type checkers
such as `mypy`. Otherwise this error appears:

```
lance_ray/datasink.py:101: error: Skipping analyzing "lance": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```